# Generated by Django 3.1.5 on 2021-02-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20210213_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
