# Generated by Django 3.1.5 on 2021-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_product_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
