# Generated by Django 3.1.5 on 2021-03-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diskon',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
