# Generated by Django 3.1.5 on 2021-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20210327_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(to='pos.Product'),
        ),
        migrations.DeleteModel(
            name='ProductPromotion',
        ),
    ]
