# Generated by Django 3.1.5 on 2021-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20210327_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(to='pos.Promotion'),
        ),
    ]
