# Generated by Django 3.1.5 on 2021-03-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20210327_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.promotion'),
        ),
    ]
