# Generated by Django 3.1.5 on 2021-03-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20210327_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.maincategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategoryOne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.subcategoryone'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategoryTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.subcategorytwo'),
        ),
    ]
