# Generated by Django 3.1.5 on 2021-03-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20210327_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktur',
            name='spending',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.spending'),
        ),
    ]
