# Generated by Django 3.1.5 on 2021-04-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20210406_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='salesTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.salestransaction'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsalestransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.product'),
        ),
    ]
