# Generated by Django 3.1.5 on 2021-04-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20210411_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsalestransaction',
            name='salesTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSales', to='pos.salestransaction'),
        ),
    ]
