# Generated by Django 3.1.5 on 2021-04-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20210411_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.promotion'),
        ),
    ]
