# Generated by Django 3.1.5 on 2021-04-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_auto_20210413_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='sales_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
