# Generated by Django 3.1.5 on 2021-04-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_faktur_cabang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cabang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.cabang', unique=True),
        ),
    ]
