# Generated by Django 3.1.5 on 2021-04-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_auto_20210414_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='reminderStockAt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
