# Generated by Django 3.1.5 on 2021-04-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_auto_20210414_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cabang',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='cabang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.cabang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='cabang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.cabang'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
