# Generated by Django 3.1.5 on 2021-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_auto_20210414_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
