# Generated by Django 3.1.5 on 2021-04-26 20:23

from django.db import migrations, models
import django.db.models.deletion
from pos.models.cabangmodels import Cabang


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='cabang',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='cabang',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='ordersent',
            name='shipment',
        ),
        migrations.AddField(
            model_name='order',
            name='cabang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.cabang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersent',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
