# Generated by Django 3.1.5 on 2021-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_auto_20210426_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturn',
            name='salesTransaction',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('REJECT', 'Rejected'), ('IN_SHIPMENT', 'Inshipment'), ('RECEIVED', 'Received')], default='IN_SHIPMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersent',
            name='status',
            field=models.CharField(choices=[('REJECT', 'Rejected'), ('IN_SHIPMENT', 'Inshipment'), ('RECEIVED', 'Received')], default='IN_SHIPMENT', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderReceived',
        ),
    ]
