# Generated by Django 3.1.5 on 2021-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_auto_20210428_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='reminderStockAt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pusatproductinventory',
            name='reminderStockAt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pusatproductinventory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
